name: barikoi_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Barikoi Maps widget.
version: 1.0.0
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barikoi_api:
    git:
      url: "git://github.com/barikoi/barikoi_api_dartlib.git"
      ref: "e73582a8682e639fbedb3ce53fdc1fb3da8afdf7"
#  mapbox_gl:  ^0.11.0
  maplibre_gl:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      ref: main
#  barikoi_maps_flutter: ^1.0.2
  geolocator: ^8.0.1
  permission_handler: ^8.3.0
  provider: ^4.0.1
#  barikoi_maps_webservice: ^0.0.16
  tuple: ^1.0.3
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
